"""
Django settings for project_template project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *
import dj_database_url
import os

# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

assert 'SECRET_KEY' in os.environ, 'Set SECRET_KEY variable in your environment file!'
SECRET_KEY = os.environ['SECRET_KEY']

# To be double sure
DEBUG = TEMPLATE_DEBUG = False
MOONSHEEP_DEVELOPMENT_MODE = False

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = []

WSGI_APPLICATION = 'project_template.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {'default': dj_database_url.config(conn_max_age=600)}

# Files from STATIC_ROOT should be served under STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
