# Generated by Django 2.0 on 2017-12-13 09:53

from django.db import migrations, models
import django.db.models.deletion
import project_template.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Védett műalkotás, védett gyűjtemény, egyéb értékes ingóság jellege')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Megnevezés')),
                ('pieces', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='db')),
                ('acquisition_type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Szerzés jogcíme')),
                ('acquisition_year', models.IntegerField()),
                ('acquisition_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='ideje')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='megnevezése')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='értéke')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='összeg')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Tartozás típusa')),
                ('description', models.TextField(verbose_name='Megnevezés')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='összeg')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_year', models.IntegerField()),
                ('financial_other', models.TextField(verbose_name='Egyéb közlendők')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Gazdasági társaság neve')),
                ('location', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Székhelye')),
                ('type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Formája')),
                ('role_beg', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Érdekeltség formája keletkezéskor')),
                ('role_now', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Érdekeltség formája jelenleg')),
                ('ownership_ratio_beg_numerator', models.IntegerField()),
                ('ownership_ratio_beg_denominator', models.IntegerField()),
                ('ownership_ratio_beg_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ownership_ratio_now_numerator', models.IntegerField()),
                ('ownership_ratio_now_denominator', models.IntegerField()),
                ('ownership_ratio_now_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('profit_share', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Nyereségből részesedés')),
                ('position', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Tisztség')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_interests', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Foglalkozás')),
                ('employer', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Munkahelye/kifizető')),
                ('active', models.BooleanField(verbose_name='Szünetelteti?')),
                ('income', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Jövedelme')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('regularity', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='gyakoriság')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', project_template.models.MyCharField(blank=True, max_length=128, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='összeg')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onligations', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Full name')),
                ('short_name', models.CharField(max_length=128, verbose_name='Short name')),
                ('parldata_id', models.CharField(max_length=64, verbose_name='External ParlData API ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Political Parties',
                'verbose_name': 'Political Party',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Full name')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='ideje')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='megnevezése')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='értéke')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=128)),
                ('area_unit', models.CharField(max_length=32)),
                ('cultivation_belterulet', models.BooleanField(verbose_name='belterület/művelés alól kivett')),
                ('cultivation_kulterulet', models.BooleanField(verbose_name='külterület')),
                ('cultivation_lakas', models.BooleanField(verbose_name='lakás/lakóház')),
                ('cultivation_other', models.CharField(max_length=128, verbose_name='cultivation: other')),
                ('building_nature_garazs', models.BooleanField(verbose_name='garázs')),
                ('building_nature_lakohaz', models.BooleanField(verbose_name='lakóház')),
                ('building_nature_udulo', models.BooleanField(verbose_name='üdülő/nyaraló')),
                ('building_nature_other', models.CharField(max_length=128)),
                ('building_area', models.CharField(max_length=128)),
                ('building_area_unit', models.CharField(max_length=32)),
                ('legal_designation_csaladi_haz', models.BooleanField(verbose_name='családi ház')),
                ('legal_designation_tarsashaz', models.BooleanField(verbose_name='társasház')),
                ('legal_designation_garazs', models.BooleanField(verbose_name='garázs')),
                ('legal_designation_other', models.CharField(max_length=128)),
                ('legal_status_tulajdonos', models.BooleanField(verbose_name='tulajdonos')),
                ('legal_status_haszonelvezo', models.BooleanField(verbose_name='haszonélvező')),
                ('legal_status_berlo', models.BooleanField(verbose_name='bérlő')),
                ('legal_status_other', models.CharField(max_length=128)),
                ('ownership_ratio_numerator', models.IntegerField()),
                ('ownership_ratio_denominator', models.IntegerField()),
                ('ownership_ratio_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', project_template.models.MyCharField(blank=True, max_length=128, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAcquisitionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', project_template.models.MyCharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_titles', to='project_template.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Takarékbetétben elhelyezett megtakarítás')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='összeg')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Értékpapír')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Névérték')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Támogatás jogosultja')),
                ('legal', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Megszerzés jogcíme')),
                ('date', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Időpontja')),
                ('provider', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Támogatást nyújtó')),
                ('purpose', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Célja')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Értéke')),
                ('currency', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='pénznem')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidies', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_general', project_template.models.MyCharField(blank=True, choices=[('motor', 'motor'), ('water_or_air', 'water_or_air')], max_length=128, null=True)),
                ('type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Gépjármű jellege')),
                ('subtype', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Típusa')),
                ('acquisition_type', project_template.models.MyCharField(blank=True, max_length=128, null=True, verbose_name='Szerzés jogcíme')),
                ('acquisition_year', models.IntegerField()),
                ('acquisition_month', models.IntegerField()),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='project_template.Declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_template.Person')),
                ('parliamentary_id', models.CharField(max_length=24, verbose_name='Parliamentary website ID')),
                ('image_url', models.URLField(max_length=256, verbose_name='Image URL')),
                ('parldata_id', models.CharField(max_length=64, verbose_name='External ParlData API ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='project_template.Party', verbose_name='Current MPs party')),
            ],
            options={
                'verbose_name_plural': 'Politicians',
                'verbose_name': 'Politician',
            },
            bases=('project_template.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='child_in_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='project_template.Declaration'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_template.Party', verbose_name='MPs party at the time of declaration import'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaration_mentions', to='project_template.Person'),
        ),
        migrations.AddField(
            model_name='debt',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='project_template.Declaration'),
        ),
        migrations.AddField(
            model_name='cash',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='project_template.Declaration'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='project_template.Declaration'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='project_template.Declaration'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='project_template.Politician'),
        ),
    ]
