# Generated by Django 2.0 on 2017-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
