# Generated by Django 2.0 on 2018-01-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
    ]
