# Generated by Django 2.2.5 on 2019-11-24 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0002_remove_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='progress',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='url',
            field=models.URLField(max_length=2048, unique=True, verbose_name='URL'),
        ),
    ]
