# Generated by Django 2.0 on 2017-12-19 01:57

from django.db import migrations, models
import django.db.models.deletion
import project_template.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0002_declaration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='acquisition_month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='acquisition_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='értéke'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='összeg'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='összeg'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='project_template.Politician'),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_beg_percent',
            field=project_template.models.PercentField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_now_percent',
            field=project_template.models.PercentField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='profit_share',
            field=project_template.models.PercentField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nyereségből részesedés'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='összeg'),
        ),
        migrations.AlterField(
            model_name='present',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='értéke'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_ratio_denominator',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_ratio_numerator',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_ratio_percent',
            field=project_template.models.PercentField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='összeg'),
        ),
        migrations.AlterField(
            model_name='security',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Névérték'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='value',
            field=project_template.models.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Értéke'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_year',
            field=models.IntegerField(blank=True),
        ),
    ]
