# Generated by Django 2.0 on 2017-12-19 02:31

from django.db import migrations
import project_template.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0003_auto_20171219_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='party',
        ),
        migrations.AddField(
            model_name='propertyacquisitiontitle',
            name='month',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyacquisitiontitle',
            name='year',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='acquisition_month',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='acquisition_year',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_beg_denominator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_beg_numerator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_now_denominator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicinterest',
            name='ownership_ratio_now_numerator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_ratio_denominator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_ratio_numerator',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyacquisitiontitle',
            name='date',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_month',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_year',
            field=project_template.models.MyIntegerField(blank=True, null=True),
        ),
    ]
